//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Default
{
    /// <summary>
    /// rptHero control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Repeater rptHero;
    /// <summary>
    /// rptBestSeller control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Repeater rptBestSeller;
}
