//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Login
{
    /// <summary>
    /// lblMessage control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblMessage;
    /// <summary>
    /// txtUsername control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtUsername;
    /// <summary>
    /// txtPassword control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtPassword;
    /// <summary>
    /// btnLogin control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnLogin;
}
