//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Shop
{
    protected global::System.Web.UI.WebControls.Repeater rptShops;
}

