//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ShopDetail
{
    protected global::System.Web.UI.WebControls.Label lblShopName;
    protected global::System.Web.UI.WebControls.Label lblAddress;
    protected global::System.Web.UI.WebControls.Label lblPhone;
    protected global::System.Web.UI.WebControls.Repeater rptProducts;
}

