//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Site
{
    /// <summary>
    /// form1 control.
    /// </summary>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    /// <summary>
    /// lnkShop control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HyperLink lnkShop;
    /// <summary>
    /// lnkOrders control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HyperLink lnkOrders;
    /// <summary>
    /// lnkInfo control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HyperLink lnkInfo;
    /// <summary>
    /// lnkLogin control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HyperLink lnkLogin;
    /// <summary>
    /// lnkRegister control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HyperLink lnkRegister;
    /// <summary>
    /// head control.
    /// </summary>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
    /// <summary>
    /// MainContent control.
    /// </summary>
    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
}
